- generator/lib/src/generator.dart
- generator/test/src/generator_test_src.dart
This will fix the bug when
```dart
@GET('/list')
@dio.Extra({'my_key': CustomValue()}
Future<void> list();
```
Produces the `extra` variable with `null` values
```dart
const _extra = <String, dynamic>{'key':null};
```
This will fix it and produce correct output
```dart
const _extra = <String, dynamic>{'key': CustomValue()};
```
Also added test cases for this
> Extra constant fix

- annotation/CHANGELOG.md
- annotation/README.md
- annotation/lib/http.dart
- example/lib/example.dart
- example/lib/example.g.dart
- generator/CHANGELOG.md
- generator/lib/src/generator.dart
- generator/pubspec.yaml
- generator/test/src/generator_test_src.dart
This will allow users to have `File` from fields, example:
```dart
/// Do not forget to add the appropriate headers
@Headers({'Content-Type': 'multipart/form-data'})
@POST("/profile")
/// This will add the image name from `image.path.split(Platform.pathSeperator).last`
Future<Response<String>> setProfileImage(@Field() File image);
```
> File form fields update

- generator/lib/src/generator.dart
- generator/test/src/generator_test_src.dart
This PR should fix #44 and every situation where a service method contains basic types such as:
```dart
@GET("...")
Future<List<String>> getListOfString();
@GET("...")
Future<List<bool>> getListOfBool();
@GET("...")
Future<List<int>> getListOfInt();
@GET("...")
Future<List<double>> getListOfDouble();
```
Adding regression tests to verify those may be necessary too.
EDIT: Added regression tests.
> Fix inner type parsing

- generator/lib/src/generator.dart
- generator/test/src/generator_test_src.dart
The previous version failed with a `List<dynamic> is not a subtype of
List<$innerReturnType>` exception.
This PR fixes the runtime issues as well as updates the tests accordingly.
> fix: fix bad cast exception

- annotation/CHANGELOG.md
- annotation/lib/http.dart
- annotation/pubspec.yaml
- example/lib/example.dart
- generator/CHANGELOG.md
- generator/lib/builder.dart
- generator/lib/src/generator.dart
- generator/pubspec.yaml
- generator/test/generator_test.dart
- generator/test/src/generator_test_src.dart
I use a custom dio interceptor to automatically convert objects to maps. My custom objects do not have `.toJson()` methods. This requires me to add custom `.toJson()` method to make retrofit work again. But my objects do not require json conversion.
Simple fix is to warn the programmer that they do not have `.toJson()` method and continue the generator.
I use [`built_value`](https://github.com/google/built_value.dart) instead of `json_serializable`. `built_value` creates serializers automatically, so I don't have `.toJson` on my custom objects
Example using automatic json conversion using dio interceptors:
```dart
class AutomaticConverterInterceptor extends Interceptor {
onRequest(options) {
if (options.data is CustomObject) {
options.data = {'id': options.data.id };
}
if (options.data is …
```
> 🐛fix (generator) Support intercepted custom object serializers

- README.md
Examples for providing query parameters were missing from the README.
> Add @Query and @Queries examples to README.md

- generator/CHANGELOG.md
- generator/lib/src/generator.dart
- generator/pubspec.yaml
- generator/test/src/generator_test_src.dart
add support for serializable args decorated with `@Queries`
support multiple `@Queries` decorators (might be useful for multiple subsets of query parameters)
closes #192
> support serializable queries

- example/lib/example.dart
- example/lib/example.g.dart
- example/lib/json_mapper_example.g.dart
- example/test/example_test.dart
- generator/CHANGELOG.md
- generator/lib/src/generator.dart
- generator/pubspec.yaml
- generator/test/src/generator_test_src.dart
support `Stream` return type
closes #149 (`Observable`s are replaced by `Stream` extensions since 0.23.x rxdart)
adjust `return` and `MethodModifier` generation 
return type | before | after
|- | - | -|
`Future` | `return Future.value(abc)` | `return abc` 
`Stream`| | `yield abc`
> support Stream return type

- generator/CHANGELOG.md
- generator/lib/src/generator.dart
- generator/pubspec.yaml
- generator/test/src/generator_test_src.dart
Add support for abstract classes with `toJson` defined in mixin/interface/superclass.
This approach is used in [freezed](https://pub.dev/packages/freezed) package.
Before: `toJson` defined indirectly wasn't found and the following warning appeared in console:
```
[WARNING] retrofit_generator:retrofit on lib/src/components/appointment/client.dart:
MySerializableAbstractClass must provide a `toJson()` method which return a Map.
It is programmer's responsibility to make sure the CancellationAppointment is properly serialized
```
> support inherited tojson

- example/bin/main.dart
- example/lib/json_mapper_example.dart
- example/lib/json_mapper_example.g.dart
- example/test/example_test.dart
- generator/lib/src/generator.dart
添加使用dartjsonmapper之后，query参数添加tojson的方法，也不在适用，建议直接把对象存储到map中，通过dio拦截器去自定义转换输入内容，通过类型判断即可将对应的object转换成对应的string输入
也解决了我说的需要string convert的问题，通过拦截器就可以自己实现了。
> 移除query自定义输入对象，使得自身对象输入到dio中，用dio拦截器可以实现自己转换数据格式

- annotation/lib/http.dart
- flutter_example/pubspec.yaml
- generator/lib/src/generator.dart
- generator/pubspec.yaml
- generator/test/src/generator_test_src.dart
this pull request solves issue #253 , I added a MapSerializable Parser. It works just like the JsonSerializable parser, but uses toMap and fromMap instead of toJson and fromJson functions. 
From experience, both ways are quite popular, and it should be important to know how to handle both of them, if we want to get to all costumers.
> added Parser.MapSrializable with toMap and fromMap functions

- generator/lib/src/generator.dart
Simple change to fix #270. 
It does not exactly meet the general logic of the generator but still provides a nice way to customize settings.
Usage remains the same:
```
@POST("publish/")
Future<void> publishContent(
@Part(name: "files") List<MultipartFile> files);
```
Calling `publishContent` is also easy:
```
void callPublishContent(File file){
return restApi.publishContent(
MultipartFile.fromFileSync(file.path, filename: file.path.split(Platform.pathSeparator).last, contentType: MediaType.parse(_getContentType(file))
)
}
```
> Allow passing a MultipartFile objects directly for custom content types

- generator/lib/src/generator.dart
Hi!
Related to the issue #275 this pull-request now can get if the reponse class have a subtype, and will generate the desired code. 
It will not affect to the usual working flow.
> Add support for json serializable generic types

- generator/lib/src/generator.dart
- generator/test/src/generator_test_src.dart
We should be able to send a body with `null` as field's value since it can be interpreted differently by remote service than the absence of the field (e.g absent  = no change, present with null = reset value) .
`JsonSerializable` already offers the possibility to include or not null values. And it's much more flexible to let programmer remove them himself if he doesn't use `JsonSerializable`
As we can see here https://github.com/trevorwang/retrofit.dart/issues/283 it can be completely blocking
> Do not remove null fields from body

- example/lib/example.g.dart
- generator/lib/src/generator.dart
- generator/pubspec.yaml
- generator/test/src/generator_test_src.dart
Since dio `4.0.0-prev2`, `data` is now a named parameter of `Options.compose`
https://github.com/flutterchina/dio/commit/9c00b8a6d972e7beae213a7e836831a303efd99f
> Fix API break with dio 4.0.0-prev3

- generator/lib/src/generator.dart
- generator/test/src/generator_test_src.dart
We wanted to split api endpoints into multiple files reflecting multiple services and use mixins for that. With class marked with `@RestApi()` implementing those mixins. In this PR I made necessary changes to also generate methods from mixins.
> Generate also mixin methods

- generator/lib/src/generator.dart
At the moment the List<List<int>> files is not actually send as file.
The filename is required at least in a PHP environment (I didn't test in other environments).
This patch add support for the fileName attribute that fix the issue.
> Add support for fileName attribute in List<List<int>>

- example/lib/example.g.dart
- generator/lib/src/generator.dart
- generator/test/src/generator_test_src.dart
I'm not sure if I've implemented it correctly, but this fixes my project, which otherwise didn't include the base URL or headers if `DioOptions` were included.
> [generator] Fix DioOptions to include the baseUrl and headers

- generator/lib/src/generator.dart
``` dart
// previous working one's
@POST("/order")
Future<ApiResponse> createOrder(@Part() Map<String, dynamic> map);
// added support for path
@POST("/order/{id}?_method=PATCH")
Future<ApiResponse> editOrder(@Path() String id, @Part() Map<String, dynamic> map);
```
> ⚡ Added Path param handling when dealing with FormData

- annotation/lib/http.dart
- example/lib/example.dart
- example/lib/example.g.dart
- flutter_example/lib/example.g.dart
- generator/lib/src/generator.dart
- generator/pubspec.yaml
添加一个cache注解，专门用来添加header的cache control属性
根据
https://developer.mozilla.org/zh-CN/docs/Web/HTTP/Headers/Cache-Control
把所有支持的客户端属性添加上，并使用other来扩展用户认为可以使用的自定义属性。
> add cache control header support

- generator/lib/src/generator.dart
- generator/test/src/generator_test_src.dart
Currently, when we declare dynamic path (with `@Path`), the generator do not include brackets for string interpolation which is fine in most cases but not always...
```dart
@GET('/images/{id}_XL.png')
Future<HttpResponse> getImage(@Path('id') String id)
```
this will generates this code :
```dart
Future<HttpResponse<dynamic>> getImage(uuid) async {
// ...
.compose(_dio.options, '/api/images/products/$uuid_XL.png',
// ...
}
```
The string interpolation expects a variable named `uuid_XL` instead of `uuid`. The generator should always add brackets. This PR fixes that and now generates : 
```dart
Future<HttpResponse<dynamic>> getImage(uuid) async {
// ...
.compose(_dio.options, '/api/images/products/${uuid}_XL.png',
// ...
}
```
> Always keep curly brackets for dynamic paths

- generator/lib/src/generator.dart
- generator/test/src/generator_test_src.dart
This PR contains following changes:
- fix null handling of MultipartFile code generation
- add some tests
Before this PR, the generated code won't be compiled by following error:
```
Error: The argument type 'Iterable<MapEntry<String, MultipartFile>>?' can't be assigned to the parameter type
'Iterable<MapEntry<String, MultipartFile>>' because 'Iterable<MapEntry<String, MultipartFile>>?' is nullable and 'Iterable<MapEntry<String, Mu
ltipartFile>>' isn't
_data.files.addAll(images?.map((i) => MapEntry('images', i)));
^
```
related: https://github.com/trevorwang/retrofit.dart/pull/272
> fix null handling of MultipartFile

- annotation/lib/http.dart
This is part of two PR's which will be fix using of Multipart annotation.
Codegen had ignored a multipart annotation before this moment.
It is caused problems with multiparts requests.
In this PR I added a field which provide form-data mime-type to MultiPart
> feat: Add mime-type to Multipart

- generator/lib/src/generator.dart
- generator/pubspec.yaml
- generator/test/src/generator_test_src.dart
This last part of my PRs which fixes a work with multipart.
I added a logic about handling contents types while code generation based on annotations.
Also, added tests.
> feat: Generate code for Multipart mime-type

- generator/lib/src/generator.dart
- generator/test/src/generator_test_src.dart
This pull request fixes an CastError that was happening when the resultType is an generic nullable
When sending fetch to dio, was forcing fetch result to be Map<String, dynamic>, causing an Error if the response was null.
Before:
`final _result = await _dio.fetch<Map<String, dynamic>>(`
After:
`final _result = await _dio.fetch<Map<String, dynamic>?>(`
I also added two tests to ensure fetch type correctly, if nullable or not.
>  Generator fix: Nullable result type

- generator/lib/src/generator.dart
- generator/test/src/generator_test_src.dart
Due to this commit 74bae83474aa421a665ea721f60463fc717ac7c3, the dart analyzer is now showing warnings about using curly braces in string interpolation when not needed.
```
info: Avoid using braces in interpolation when not needed.
```
This PR adds an `ignore_for_file` rule to suppress these warnings.
> [generator] Adds a `ignore_for_file` rule to suppress the analyzer warnings for the generated files.

- example/lib/example.g.dart
- generator/lib/src/generator.dart
- generator/test/src/generator_test_src.dart
I encounter a problem when trying to deserialize a generic List. My sample codes:
**Generic model:**
```dart
@JsonSerializable(genericArgumentFactories: true)
class ApiResponse<Data, Meta>{
final Data? _data;
final Meta? _meta;
final bool _success;
const ApiResponse({
Data? data,
Meta? meta,
bool success = false,
})  : _data = data,
_meta = meta,
_success = success;
Data? get data => _data;
Meta? get meta => _meta;
ApiError? get error => _error;
bool get success => _success;
factory ApiResponse.fromJson(
Map<String, dynamic> json,
Data Function(Object? json) dataFromJson,
Meta Function(Object? json) metaFromJson,
) =>  _$ApiResponseFromJson(json, dataFromJson, metaFromJson);
}
```
**Retrofit class1:**
```dart
@RestApi()
abstract class SearchApi1 {
factory SearchApi1(Dio dio, {String …
```
> Fix bug deserialize List

- generator/lib/src/generator.dart
- generator/test/src/generator_test_src.dart
I see that there is 
```
if (options is RequestOptions) {
return options as RequestOptions;
}
```
in `newRequestOptions`. However, when I do
```
@POST('/url')
Future<MyResponse> createSale(
@Body() MyRequest body, [
@DioOptions() RequestOptions? dioOption,
]);
``` 
I am getting 
```
Error: The argument type 'RequestOptions?' can't be assigned to the parameter type 'Options?'.
setel_services/…/setel_hub_gateway/api.g.dart:25
- 'RequestOptions' is from 'package:dio/src/options.dart' ('../../../.pub-cache/hosted/pub.dartlang.org/dio-4.0.4/lib/src/options.dart').
package:dio/src/options.dart:1
- 'Options' is from 'package:dio/src/options.dart' ('../../../.pub-cache/hosted/pub.dartlang.org/dio-4.0.4/lib/src/options.dart').
package:dio/src/options.dart:1
final newOptions = …
```
> feat: change `newRequestOptions` argument to Object.

- generator/pubspec.yaml
Packages are slowly starting to use the latest analyzer version and it would soon (again) become an incompatibility problem.
I have widened the version range to include both 3 and 4 - but if you want to allow only 4, I can change that.
> support analyzer 4.0.0

- generator/lib/src/generator.dart
- generator/test/src/generator_test_src.dart
We have a massive project with hundreds of packages, and each package has 5-20 API calls. Efficient development at such a scale would not be possible without heavy usage of code generation. And retrofit package plays a crucial role in our project. Thanks for such a fantastic tool!
To push code minimization even further, we developed an approach with the usage of `@Exra` request annotations and `Dio` interceptors. We declare a `const` value based on `Extra`:
```dart
const authenticatedRequest = Extra({'append-token': true});
```
And a `Dio` interceptor that awaits for `append-token` key:
```dart
class AppendTokenInterceptor extends Interceptor {
AppendTokenInterceptor(this._authService);
final AuthService _authService;
static const _appendTokenExtraKey = 'append-token';
@override …
```
> Multiple @Extra and @Headers

- .github/workflows/test.yml
- generator/lib/src/generator.dart
- generator/pubspec.yaml
- generator/test/generator_test.dart
- retrofit/pubspec.yaml
In my project I use freezed and also analyzer version 5(#499).  So I removed deprecated methods to their alternative.
- assertFinal -> declareFinal
- assertVar -> declareVar
- assertConst -> declareConst
- element -> element2
- enclosingElement -> enclosingElement3
Also, to use analyzer 4.6.0 and higher, need Dart 2.17
> Update analyzer and Dart version to 2.17

- generator/lib/src/generator.dart
It will fix this issue. https://github.com/trevorwang/retrofit.dart/issues/547
I made the generator to make the data null when there is no body.
> Make data `null` when there is no body

- generator/lib/src/generator.dart
when use headers annotation, generator code cann't transform double、int、bool type to genetated code. So fix like this
> support multi parameter types for headers

- generator/lib/src/generator.dart
- generator/test/src/generator_test_src.dart
如这样一个接口
Future<ApiResult<List>> getApiResultGenericsInnerTypeNullable();
当返回值不是一个List而是一个Object时：
{
"code": 0,
"data": {},
"msg": ""
}
解析报错，同时开发者没办法去处理这个异常
> fix the problem when deserialize an object to list

- generator/lib/src/generator.dart
Adding ability to restore previous behaviour before [this](https://github.com/trevorwang/retrofit.dart/pull/549) commit.
Can be set via this in `build.yaml`
```
targets:
$default:
builders:
retrofit_generator|retrofit:
options:
empty_request_body: true
```
> Add `emptyRequestBody` option

- README.md
I received the following warning message from Flutter version 3.7.10 with Dart version 2.18:
```
[WARNING] json_serializable on lib/screens/example/example.dart:
You are missing a required dependency on json_annotation in the "dependencies" section of your pubspec with a lower bound of at least "4.8.0”
```
> Add json_annotation dependency

- example_relative_base_url/analysis_options.yaml
- example_relative_base_url/build.yaml
- example_relative_base_url/lib/api_result.dart
- example_relative_base_url/lib/example.dart
- example_relative_base_url/mono_pkg.yaml
- example_relative_base_url/pubspec.yaml
- example_relative_base_url/test/example_test.dart
- example_relative_base_url/test/task_data.dart
- generator/lib/src/generator.dart
- generator/test/src/generator_test_src.dart
- retrofit/lib/http.dart
This pull request introduces the feature of supporting a relative base path in the @RestApi annotation. Now it's possible to specify a relative base path for the client, allowing greater flexibility in route configuration.
```dart
@RestApi(baseUrl: 'tasks')
abstract class TasksRestClient {
@GET('/{id}')
Future<List<Task?>> getTaskById();
@GET('/')
Future<List<Task>> getTasks();
....
}
```
This update has been implemented by incorporating a mechanism to correctly interpret and combine the relative base path with the configured baseUrl in the dio instance. A new test has been added to ensure proper handling of the base path. This enhancement provides a more convenient way to organize and structure routes within our clients, enabling a more modular and scalable implementation.
> Add support for relative base path in @RestApi

- generator/lib/src/generator.dart
- generator/test/src/generator_test_src.dart
> fix: generate datetime in query parameters as iso string

- generator/CHANGELOG.md
- generator/pubspec.yaml
incremented generator pubspec version to release the previously merged fix #580
> chore: incremented pubspec version

- example/pubspec.yaml
- example_relative_base_url/pubspec.yaml
- generator/CHANGELOG.md
- generator/lib/src/generator.dart
- generator/pubspec.yaml
- generator/test/src/generator_test_src.dart
Vesion 7.0.7 has breaking change.
I want to use `toJson()` if it exists.
-----
```dart
enum ToJsonEnum {
plus(1),
minus(-1),
;
const ToJsonEnum(this.value);
final int value;
int toJson() => value;
}
@RestApi()
abstract class TestQueryParamEnumToJson {
@GET('/test')
Future<void> getTest(@Query('test') ToJsonEnum? status);
}
```
7.0.6 and 7.0.8 generates `final queryParameters = <String, dynamic>{r'test': status?.toJson()};`.
7.0.7 generates `final queryParameters = <String, dynamic>{r'test': status?.name};`.
> Use `toJson()` instead of `.name` if enums have `toJson()`.

- example_protobuf/lib/example.dart
- example_protobuf/lib/proto/params.pb.dart
- example_protobuf/lib/proto/params.pbenum.dart
- example_protobuf/lib/proto/params.pbjson.dart
- example_protobuf/lib/proto/params.pbserver.dart
- example_protobuf/lib/proto/result.pb.dart
- example_protobuf/lib/proto/result.pbenum.dart
- example_protobuf/lib/proto/result.pbjson.dart
- example_protobuf/lib/proto/result.pbserver.dart
- example_protobuf/proto/params.proto
- example_protobuf/proto/result.proto
- generator/lib/src/generator.dart
- generator/test/src/generator_test_src.dart
1、remove unused contentType in header and move gen code for requestBody contentType
2、add protobuf mineType parameters messageType for proxy tools (https://stackoverflow.com/questions/30505408/what-is-the-correct-protobuf-content-type,https://docs.proxyman.io/advanced-features/protobuf)
> feat: add protobuf mineType parameters messageType for proxy tools

- generator/lib/src/generator.dart
- generator/test/src/generator_test_src.dart
1、fix gen code error on  MapSerializable、DartJsonMapper、FlutterCompute with pb support
2、add test for every Parse for PB support
> fix: pb support error on MapSerializable、DartJsonMapper、FlutterCompute

- generator/lib/src/generator.dart
this is the fix for https://github.com/trevorwang/retrofit.dart/issues/559
and it's a patch continued from https://github.com/trevorwang/retrofit.dart/pull/596
> Use `toJson()` instead of .name if `@Path` enums have `toJson()`

- generator/lib/src/generator.dart
I have a Generic API Model that couldn't be used in a Computed Data Source(using retrofit.Parser.FlutterCompute) because I didn't have a way to pass the fromJson factory of the T.
I tried to extend T with an abstract class, but it doesn't work. I also tried passing the factory method as a parameter to the deserialization method, it didn't work as well.
I finally made it by changing the `_generateRequest` method to return a name that I could use to have a unique method for every T type in ApiModel<T> by removing the `<`and `>`.
```
PaginatedApiData<SampleApiData> deserializePaginatedApiDataSampleApiData(
Map<String, dynamic> json,
) =>
PaginatedApiData.fromJson(json, SampleApiData.fromJson);
PaginatedApiData<SampleTestApiData>
deserializePaginatedApiDataSampleTestApiData(
Map<String, …
```
> Fix Flutter Compute Generator to allow Multiple Functions for Generic Objects

- README.md
Added documentation in the readme for the feature introduced in the PR  https://github.com/trevorwang/retrofit.dart/pull/579
> Add relative API baseUrl section in README

- generator/lib/src/generator.dart
Use 'const' for final variables initialized to a constant value. Try replacing 'final' with 'const'. #652
> For constant null, declareFinal is replaced by declareConst

- generator/CHANGELOG.md
- generator/lib/src/generator.dart
- generator/pubspec.yaml
- generator/test/src/generator_test_src.dart
- retrofit/CHANGELOG.md
- retrofit/lib/dio.dart
- retrofit/pubspec.yaml
Add @Extras() to pass extra options to dio interceptors for each request as parameters.
The code is mostly copy-pasted from the @Queries implementation.
Fix https://github.com/trevorwang/retrofit.dart/issues/445
Usage is the same as @Queries
```
@GET("/get")
Future<String> foo(@Extras() Map<String, dynamic> extras)
```
> feat: Add support @Extras()

- generator/lib/src/generator.dart
- generator/test/src/generator_test_src.dart
Currently it is not possible to have a parameter named `value` in methods annotated with `@GET/POST/PUT...`
I'm in the complex process of setting up retrofit.dart to generate an API Client from an OpenAPI specification file, which itself is generated by [api-platform](https://github.com/api-platform/api-platform), the boilerplate code of which is also generated. (by a custom built code-generator based on [php-generator](https://github.com/nette/php-generator))
To make a long story shorter, this means that the method parameters in my RestClient have identifiers based on the column names of the underlying database. Here is an example of such a method : 
```dart
/// Updates the ExampleEndpoint resource.
@PATCH('/api/example_endpoint/{idExampleEndpoint}')
Future<ExampleEndpoint> …
```
> Allow to have 'value' as a parameter identifier in annotated methods

- generator/lib/src/generator.dart
Currently there is no null checking when retrofit works on a request body.
https://github.com/trevorwang/retrofit.dart/issues/662
This small refactor separates the process of setting the data variable into 3 parts
1. Declaration: `final data = `
2. Value: `body.map((e) => e.toJson()).toList()`
3. Post Assignment `data.removeWhere((k, v) => v == null);`
This way we can assign the data value using a ternary expression:
```dart
final _data = body == null ? null : body.map((e) => e.toJson()).toList();
```
and also run the Post Assignment in a type safe manner:
```dart
if (_data != null) {
data.removeWhere((k, v) => v == null);
}
```
This change is completely backwards compatible, using this with a required, non-nullable body results in the exactly same code.
> Assign data with null safety

- generator/lib/src/generator.dart
Hello,
This is my first contribution to retrofit or any other dart open-source project so sorry for any inconvenience.
In my use case we are sending several different content-types in multipart request. So the use of the content-type header for each part is very important. 
The way I got around this so far is  using `List<MultipartFile>` and building out my own objects with content type as that seems to have worked.
I thought others might find this useful so I tweaked the generator a bit. 
When content type is present instead of serializing into a simple map entry I create a MultipartFile from string and add the content-type.
This is just a PR to gauge the possibility of this being merged. I know I still have to handle the other types.
I await your input.
> Use the available content type part annotation field for objects

- generator/lib/src/generator.dart
If we have a request like this:
```dart
@MultiPart()
@POST('/api/some/path/')
Future<SomeResponse> requestName({
@Part(name: 'full_name') required String fullName,
@Part(name: 'birth_date') required DateTime birthDate,
```
we'll get a `toJson() method have to add to DateTime` Exception.
If part param doesn't have the `toJson()` method, we have to check whether this is DateTime. If so, we use a`toIso8601String` method.
> fix: Add Missing Mapping of DateTime in Multipart

- generator/lib/src/generator.dart
- retrofit/lib/error_logger.dart
Sometimes, the back-end changes the response structure unexpectedly. For example, our app expects this:
```json
{
"id": "0",
"name": "Name"
}
```
but we get this instead:
```json
{
"id": 0,
"name": "Name"
}
```
Logging these discrepancies would be really useful. To make the logs as helpful as possible, we need to capture:
* Request details (path, URI, params, etc.); 
* Parsing error details (we can use `CheckedFromJsonException` from `json_serializable`).
The most logical place for such logging is within the client.
Let's introduce a new entity - `ParseErrorLogger` :
```dart
import 'package:dio/dio.dart';
/// Base class for logging errors that occur during parsing of response data.
abstract class ParseErrorLogger {
/// Logs an error that occurred during parsing of response data.
/// 
/// …
```
> feat(generator): Add ParseErrorLogger 

- generator/lib/src/generator.dart
#676 I am passing baseUrl through `@RestApi`, it is showing a warning that I am not using the baseUrl parameter from the Auto-generated(g.dart) file
With the following comment, this issue can be resolved 
`// ignore_for_file: unused_element`
Output after change:
```// GENERATED CODE - DO NOT MODIFY BY HAND
part of 'api_service.dart';
// **************************************************************************
// RetrofitGenerator
// **************************************************************************
// ignore_for_file: unnecessary_brace_in_string_interps,no_leading_underscores_for_local_identifiers,unused_element
class _ApiService implements ApiService {
_ApiService(
this._dio, {
this.baseUrl,
}) {
baseUrl ??= 'https://fakestoreapi.com';
}
```
> Unused baseUrl parameter warning fix

- generator/lib/src/generator.dart
During file upload, I noticed an abnormally long processing and opening time. This PR introduces a modification to improve the performance of file opening before the upload.
Replaced the existing file opening method with a more efficient method.
I conducted tests by uploading a 2MB file. Here are the comparative results:
```dart
final _data = Stream.fromIterable(gpxFile.readAsBytesSync().map((i) => [i]));
```
File opening and processing time: between 1min30s to 2 minutes
```dart
final _data = gpx.openRead();
```
File opening and processing time: < 5 seconds
- Use the application to upload a test file, ideally 1MB or larger.
- Note the processing and opening times before and after applying the modifications.
- This modification should significantly improve performance for large files
- No …
> fix(UploadFile): Improve File Opening Performance During Upload

- example/lib/auth_client.dart
- example/lib/example.dart
- example_dartmapper/lib/example.dart
- example_dartmapper/lib/json_mapper_example.dart
- example_protobuf/lib/example.dart
- example_relative_base_url/lib/example.dart
- generator/lib/src/generator.dart
- generator/test/src/generator_test_src.dart
- retrofit/lib/error_logger.dart
- retrofit/lib/retrofit.dart
Sometimes, the back-end changes the response structure unexpectedly. For example, our app expects this:
```json
{
"id": "0",
"name": "Name"
}
```
but we get this instead:
```json
{
"id": 0,
"name": "Name"
}
```
Logging these discrepancies would be really useful. To make the logs as helpful as possible, we need to capture:
* Request details (path, URI, params, etc.); 
* Parsing error details (we can use `CheckedFromJsonException` from `json_serializable`).
The most logical place for such logging is within the client.
Let's introduce a new entity - `ParseErrorLogger` :
```dart
import 'package:dio/dio.dart';
/// Base class for logging errors that occur during parsing of response data.
abstract class ParseErrorLogger {
/// Logs an error that occurred during parsing of response data.
/// 
/// …
```
> feat(generator): Add ParseErrorLogger

- README.md
- generator/CHANGELOG.md
- generator/lib/retrofit_generator.dart
- generator/lib/src/generator.dart
- generator/pubspec.yaml
- generator/test/src/query.pb.dart
- retrofit/CHANGELOG.md
- retrofit/lib/error_logger.dart
- retrofit/lib/http.dart
- retrofit/lib/retrofit.dart
- retrofit/pubspec.yaml
In analyzer 6.5.0 they remove support for `getDisplayString(withNullability: false)`:
`String getDisplayString` Only non-nullable by default mode is supported.
Analyzer 6.5.0 and higher support Dart ^3.3 and I also update sdk and replace tuple with records
> Fix deprecations of `withNullability`

- example_dartmapper/pubspec.yaml
- generator/CHANGELOG.md
- generator/lib/src/generator.dart
- generator/pubspec.yaml
- generator/test/src/generator_test_src.dart
- retrofit/CHANGELOG.md
- retrofit/lib/dio.dart
- retrofit/pubspec.yaml
This PR adds functionality that allows developers to pass extras with requests using custom classes.
Imagine you want every request in your app to include some additional metadata, such as an id and a region. Without this feature, you would have to annotate each request manually with something like Extra({'id': '1234', 'region': 'ng'}). While this approach works, it requires passing the key-value pairs each time, which introduces several risks:
Developers may inadvertently misspell a key (e.g., regoin instead of region).
A required key might be forgotten or omitted.
The repeated manual input increases the chance of inconsistency,
Introduce `TypedExtras`, which developers can extend to provide extras in a structured and type-safe manner. By defining fields within the custom class, …
> Feat: Enable passing in Extras using Custom Annotations

- generator/CHANGELOG.md
- generator/lib/src/generator.dart
- generator/test/src/generator_test_src.dart
This PR enhances the flexibility of the Retrofit generator by allowing multiple TypedExtras subclass to be used on a single method. Previously, only one TypedExtras subclass was supported, limiting the ability to organise and group extra parameters. This change brings the behavior of TypedExtras subclass in line with how Extra subclasses are handled.
- Updated the logic of `_getMapFromTypedExtras` to include all @TypedExtras data
- Maintained backward compatibility with existing implementation
- The `_getMapFromTypedExtras` method now iterates through all @TypedExtras annotations on a method, extracting and combining their field values.
- In case of conflicting keys across multiple @TypedExtras annotations, the later annotations take precedence.
- Greater flexibility in organising and …
> Add Support for multiple TypedExtra subclasses.

- generator/lib/src/generator.dart
Fixes [#717](https://github.com/trevorwang/retrofit.dart/issues/717)
This can add a generate code to check the if condition of the nullable File type when we write like that `@Part(name: "photo") File? photo`. 
After we run the build runner, it will generate the code to check this File type to the optional field.
```
if (photo != null) { // generate this line
_data.files.add(MapEntry(
'photo',
MultipartFile.fromFileSync(
photo.path,
filename: photo.path.split(Platform.pathSeparator).last,
),
));
}  // generate this line
> [generator] add nullable of File type @Part

- generator/lib/src/generator.dart
- generator/test/src/generator_test_src.dart
This pull request introduces an `unnecessary_string_interpolations` rule aimed at suppressing warnings when URLs are directly provided through the `Path` field. Previously, using interpolation on paths in functions such as:
```dart
@GET('{url}')
@DioResponseType(ResponseType.bytes)
Future<List<int>?> loadAsBytes(
@Path('url') String url,
);
```
would result in:
```dart
.compose(
_dio.options,
'${url}',
queryParameters: queryParameters,
data: _data,
)
```
which triggers an `"Unnecessary use of string interpolation"` warning.
With this new rule, these warnings are prevented, improving code clarity and ensuring paths are treated as intended without redundant alerts.
> [generator] Adds a `unnecessary_string_interpolations` rule to suppress the analyzer warnings for the generated files.

- generator/CHANGELOG.md
- generator/lib/src/generator.dart
- generator/pubspec.yaml
- generator/test/src/generator_test_src.dart
Nested Attribute Mapping: Adds the ability to parse and include nested non primitive objects.
Example:
```dart
@RestApi()
abstract class TypedExtrasTest {
@DummyTypedExtras(
id: '1234',
config: Config(
date: '24-10-2024',
type: 'analytics',
shouldReplace: true,
subConfig: {'date': '24-11-2025'},
),
)
@GET('path')
Future<void> list();
}
```
> Feat: support nested non-primitive types for TypedExtras

- README.md
- generator/CHANGELOG.md
- generator/lib/src/generator.dart
- generator/pubspec.yaml
- generator/test/src/generator_test_src.dart
- retrofit/CHANGELOG.md
- retrofit/lib/call_adapter.dart
- retrofit/lib/http.dart
- retrofit/lib/retrofit.dart
- retrofit/pubspec.yaml
Introduced CallAdapters, a feature that allows you to adapt the return type of a network call from one type to another.
For example:
`Future<User>` → `Future<Result<User>>`.
A CallAdapter takes the original return type R and transforms it into a new type T. This is particularly useful when working with response wrappers like Either, Result, or ApiResponse.
Sample Code:
```dart
class MyCallAdapter<T> extends CallAdapter<Future<T>, Future<Result<T>>> {
@override
Future<Result<T>> adapt(Future<T> Function() call) async {
try {
final response = await call();
return Result<T>.ok(response);
} catch (e) {
return Result.err(e.toString());
}
}
}
@RestApi(callAdapter: MyCallAdapter)
abstract class RestClient {
factory RestClient(Dio dio, {String? baseUrl}) = _RestClient;
@GET('/') …
```
> Implemented Call Adapter

- README.md
- generator/CHANGELOG.md
- generator/lib/src/generator.dart
- generator/pubspec.yaml
- generator/test/src/generator_test_src.dart
- retrofit/CHANGELOG.md
- retrofit/lib/call_adapter.dart
- retrofit/lib/http.dart
- retrofit/lib/retrofit.dart
- retrofit/pubspec.yaml
This reverts commit e8bdb48705662810b48ac911f9ba5584967aa2be.
> feat: "Implemented Call Adapter (#729)" (#730)

- generator/CHANGELOG.md
- generator/lib/src/generator.dart
- generator/test/src/generator_test_src.dart
This PR fixes an issue with path parameter replacement in `RetrofitGenerator`.
This modification allows for multiple occurrences of the same Path Parameter to be properly replaced in API Endpoint URL.
- Changed `replaceFirst` to `replaceAll` in the path parameter replacement logic
- Added test cases to verify multiple path parameter replacements
https://x.com/YumNumm/status/1880651949508612347
---
Before: 
```dart
@Get('/users/{id}/posts/{id}')
Future<ResponseType> getUserPosts(@Path('id') String id);
// Only replaces first occurrence: `/users/123/posts/{id}`
```
After: 
```dart
@Get('/users/{id}/posts/{id}')
Future<ResponseType> getUserPosts(@Path('id') String id);
// Replaces all occurrences: `/users/123/posts/123`
```
N/A
> fix(generator): generates invalid code for the same path parameter appears multiple times 

- generator/lib/src/generator.dart
support  generic class with void. example ApiResponse<void>
@JsonSerializable(genericArgumentFactories: true)
class ApiResponse<T> {
final int code;
final String? msg;
@JsonKey(name: 'data')
final T data;
}
@POST("/app/user/sendRegisterCode")
Future<ApiResponse<void>> sendRegisterCode(@Body() Map<String, dynamic> body);
> updat: support generic with void

- generator/lib/src/generator.dart
- generator/lib/src/generator.dart~
- add `.toString()` to non-string lists in multipart request
- solve exception when use list of enum in multipart request
> add `.toString()` to non-string lists in multipart request

- generator/CHANGELOG.md
- generator/lib/src/generator.dart
- generator/pubspec.yaml
- generator/test/src/generator_test_src.dart
- The CallAdapter should use "R" in CallAdapter<R, T> when trying to figure out if to use a "return" or "yield", not the return type of the request Method. E.g. in the image below it should use the type in green circle, instead of the one in the red circle.
- This PR also makes the test case more elaborate, to cover this case.
> Fix issue of callAdapter using yield/return incorrectly

- generator/lib/src/generator.dart
- generator/test/src/generator_test_src.dart
Hi @trevorwang 
Current generator produces lint warnings for
```
A value for optional parameter 'errorLogger' isn't ever given.
```
This PR adds `unused_element_parameter` to ignore section
> add unused_element_parameter to ignore section

- generator/CHANGELOG.md
- generator/lib/src/generator.dart
- generator/pubspec.yaml
- generator/test/src/generator_test_src.dart
- retrofit/CHANGELOG.md
- retrofit/lib/http.dart
- retrofit/pubspec.yaml
About https://github.com/trevorwang/retrofit.dart/discussions/752.
Added `@BodyExtra` annotation: Add individual fields to request body without defining complete DTO classes
- Support for adding dynamic fields to existing request bodies
- `expand` parameter (default: false) to control object field flattening behavior
Example(Combine fields):
```dart
@http.POST('/path/')
Future<String> updateValue(@BodyExtra('id') int id, @BodyExtra('value') String value);
```
Request body result:
```json
{"id": 123, "value": "some value"}
```
Example(Combine objects):
```dart
// pseudocode
class User {
int userId;
String userName;
}
class Settings {
int a;
int b;
}
@http.POST('/path/')
Future<String> updateValue(
@BodyExtra('user', expand: true) User user, 
@BodyExtra('settings', expand: true) Settings …
```
> feat: added `@BodyExtra` generator

- README.md
- generator/lib/src/generator.dart
- generator/test/src/generator_test_src.dart
Solves #777 
After 9.5.0, the enum generation was changed to no longer call '.name', instead it relies on 'toString()'.
However, in '@Part' annotations, the resulting generated code was having a compile time mismatch due to FormData being a map of String to String. So I changed it to call '.toString()' directly to solve this issue.
However, there is still breaking changes for many people's code base because of 9.5.0 without their knowledge, for example #780. If the enums don't override the '.toString()' method, the resulting string in places such as '@Path' annotation with be 'MyEnum.a' rather than 'a'. I don't know whether there is a way to check if an enum class has overridden the toString or not. If there is, we can check that and use the toString or call '.name' like before.
For now, …
> Fix enum issue
