generator/lib/src/generator.dart
I was unable to get your code to compile, however, I think this will suffice for the FormData body fix. If you could please review, make any necessary changes, and generate a new release. Thanks.
=> Adding check when generating Request Body to interpret if body is of type FormData and if so, assign it to the data variable

example/lib/example.dart, example/lib/example.g.dart, generator/lib/src/generator.dart, generator/test/src/generator_test_src.dart
=> feat: add object support for @Body() annoation

example/analysis_options.yaml, example/bin/main.dart, example/lib/example.dart, example/lib/example.g.dart, example/lib/http_get.g.dart, generator/CHANGELOG.md, generator/lib/src/generator.dart, generator/pubspec.yaml, generator/test/src/generator_test_src.dart
=> feat: strong mode support

generator/CHANGELOG.md, generator/pubspec.yaml
=> 🚑fix (generator) Pin dio version to `2.1.16`

.circleci/config.yml, .drone.yml, .travis.yml, example/bin/main.dart, example/lib/example.dart, example/lib/example.g.dart, generator/CHANGELOG.md, generator/lib/src/generator.dart, generator/pubspec.yaml, generator/test/src/generator_test_src.dart
Temporarily disable gen test since it doesn't work on dart 2.5
#56
=> feat: dio 3.0 support

annotation/CHANGELOG.md, annotation/lib/dio.dart, annotation/pubspec.yaml, example/bin/main.dart, example/lib/example.dart, example/lib/example.g.dart, generator/CHANGELOG.md, generator/lib/src/generator.dart, generator/pubspec.yaml
=> feat: add response type support

generator/lib/src/generator.dart, generator/pubspec.yaml
=> fix: fix file upload issue

example/lib/example.dart, example/lib/example.g.dart, generator/lib/src/generator.dart, generator/pubspec.yaml
=> fix: fix contentType issue

example/lib/example.dart, example/lib/example.g.dart, example/pubspec.yaml, generator/CHANGELOG.md, generator/lib/src/generator.dart, generator/pubspec.yaml, generator/test/main_test.dart, generator/test/src/generator_test_src.dart, generator/test/src/task_data.dart
=> feat: enable integration test

example/lib/demo.dart, example/lib/demo.g.dart, example/lib/example.g.dart, generator/lib/src/generator.dart, generator/test/demo_test.dart, generator/test/src/generator_test_src.dart
#76  I have added an example base on your json data. And it works.
=> feat: add demo & test for list nested in a class

annotation/lib/http.dart, example/lib/example.dart, example/lib/example.g.dart, generator/pubspec.yaml, generator/test/src/generator_test_src.dart
=> feat: add HEAD and OPTIONS methods

README.md, annotation/CHANGELOG.md, annotation/lib/http.dart, annotation/pubspec.yaml, example/lib/example.dart, example/lib/example.g.dart, generator/CHANGELOG.md, generator/lib/src/generator.dart, generator/pubspec.yaml, generator/test/src/generator_test_src.dart
=> fix: fix url encoded form data

generator/lib/src/generator.dart, generator/test/src/generator_test_src.dart
=> feat: add  null-aware access to nullable parameter

README.md, example/lib/example.dart, example/lib/example.g.dart, generator/CHANGELOG.md, generator/lib/src/generator.dart, generator/pubspec.yaml, generator/test/src/generator_test_src.dart
=> fix: revert to use displayName

example/lib/example.dart, example/lib/example.g.dart, generator/lib/src/generator.dart, generator/pubspec.yaml, generator/test/src/generator_test_src.dart
=> feat: json stringify models in formdata

example/lib/example.dart, example/lib/example.g.dart, generator/lib/src/generator.dart
=> fix: add part value to replace files key

example/lib/example.dart, example/lib/example.g.dart, generator/lib/src/generator.dart, generator/pubspec.yaml, generator/test/src/generator_test_src.dart
=> fix: add null check on optional file

example/lib/example.dart, example/lib/example.g.dart, generator/CHANGELOG.md, generator/lib/src/generator.dart, generator/pubspec.yaml, generator/test/src/generator_test_src.dart
=> fix: weird workaround for brackets in formdata

example/lib/example.dart, example/lib/example.g.dart, generator/lib/src/generator.dart, generator/pubspec.yaml, generator/test/src/generator_test_src.dart
=> fix: add non-string support

example/lib/example.dart, example/lib/example.g.dart, generator/lib/src/generator.dart, generator/pubspec.yaml, generator/test/src/generator_test_src.dart
=> fix: formdata optional file

example/lib/example.dart, example/lib/example.g.dart, generator/lib/src/generator.dart, generator/test/src/generator_test_src.dart
=> fix: formdata nullable parameters

.gitignore, example/lib/example.dart, example/lib/example.g.dart, generator/lib/src/generator.dart, generator/pubspec.yaml
=> fix: ignore return type when there's no type in future

example/lib/example.dart, example/lib/example.g.dart, generator/lib/src/generator.dart, generator/pubspec.yaml
=> fix: remvove nullable field

generator/lib/src/generator.dart
should fix https://github.com/trevorwang/retrofit.dart/issues/221
=> fix: Ignore null attributes using @Body()

generator/lib/src/generator.dart, generator/pubspec.yaml
=> revert:  Ignore null attributes using @Body()

example/lib/example.dart, example/lib/example.g.dart, generator/lib/src/generator.dart, generator/pubspec.yaml, generator/test/src/generator_test_src.dart
=> feat: body list content support

example/lib/example.g.dart, generator/lib/src/generator.dart, generator/test/src/generator_test_src.dart
=> fix List<Object> gen code

generator/lib/src/generator.dart
Reverts trevorwang/retrofit.dart#282
=> Revert "Add support for json serializable generic types"

generator/lib/src/generator.dart, generator/test/src/generator_test_src.dart
This is the same as [286](https://github.com/trevorwang/retrofit.dart/pull/286) but with tests, hope it helps
=> Fix inner primitive and dynamic generic types

generator/lib/src/generator.dart, generator/test/src/generator_test_src.dart
Fix for this Issue [#291](https://github.com/trevorwang/retrofit.dart/issues/291)
=> Fix GenericArgumentFactories, in json serializable

.circleci/config.yml, .drone.yml, annotation/lib/http.dart, annotation/pubspec.yaml, example/lib/example.dart, example/lib/example.g.dart, example/pubspec.yaml, example/test/example_test.dart, example_dartmapper/pubspec.yaml, flutter_example/lib/example.dart, flutter_example/lib/example.g.dart, flutter_example/lib/main.dart, flutter_example/lib/mock_adapter.dart, flutter_example/pubspec.yaml, generator/lib/src/generator.dart, generator/pubspec.yaml, generator/test/src/generator_test_src.dart
Initial attempt at adding nullsafety support to the retrofit generator
=> [WIP]Feature/Nullsafety

.circleci/config.yml, annotation/pubspec.yaml, example/pubspec.yaml, generator/lib/src/generator.dart, generator/pubspec.yaml
The generator now runs in sound null safe mode!
=> Upgrade dependencies to null-safe code builder etc.

example/lib/example.dart, example/lib/example.g.dart, generator/lib/src/generator.dart, generator/test/src/generator_test_src.dart
The return value type supports:
- Future<String?>
- Future<User?>
- Future<HttpReponse<String?>>
- etc.
=> Support return nullable value.

example/lib/example.dart, example/lib/example.g.dart, generator/lib/src/generator.dart
=> Fix receiveProgress for generator

README.md, docs/index.html
I have read your awesome package and I want to fix some minor typo for it
=> Fix typo in README and docs

.circleci/config.yml, generator/lib/src/generator.dart
currently you can't add nullable list of int
but with this PR you will be able to use sth like this:
```
@Part() List<int>? attach,
```
=> nullable list of int was added to generator

.circleci/config.yml, README.md, annotation/lib/dio.dart, annotation/pubspec.yaml, docs/index.html, example/lib/example.dart, example/pubspec.yaml, example/test/example_test.dart, example_dartmapper/bin/main.dart, example_dartmapper/lib/example.dart, example_dartmapper/lib/json_mapper_example.dart, example_dartmapper/test/example_test.dart, flutter_example/lib/example.dart, flutter_example/lib/mock_adapter.dart, generator/lib/src/generator.dart, generator/pubspec.yaml, generator/test/src/generator_test_src.dart
Since `dio` seems no longer maintained, use the fork `dio_http` instead
=> Replace dio by dio_http

example/lib/example.dart, example/lib/example.g.dart, generator/lib/src/generator.dart, generator/pubspec.yaml
fix: generic use toJson method in `Post` @Body when used with json_serializable annotation `genericArgumentFactories`
=> fix generic type with toJson method in @Body param

README.md, annotation/lib/dio.dart, annotation/pubspec.yaml, docs/index.html, example/lib/example.dart, example/pubspec.yaml, example/test/example_test.dart, example_dartmapper/bin/main.dart, example_dartmapper/lib/example.dart, example_dartmapper/lib/json_mapper_example.dart, example_dartmapper/test/example_test.dart, flutter_example/lib/example.dart, flutter_example/lib/mock_adapter.dart, generator/lib/src/generator.dart, generator/pubspec.yaml, generator/test/src/generator_test_src.dart
Reverts trevorwang/retrofit.dart#397
=> Revert "Replace dio by dio_http"

generator/lib/src/generator.dart, generator/test/src/generator_test_src.dart
Deal with the nullable list `List<File>? images`
```
@POST('/tasks/')
@MultiPart()
Future<Poll?> createPoll({
@Part() String? question,
@Part() List<File>? images,
});
```
=> For @Part() List<File>? images

.circleci/config.yml, annotation/pubspec.yaml, example/pubspec.yaml, generator/pubspec.yaml
=> update analyzer dependency

generator/lib/src/generator.dart, generator/test/src/generator_test_src.dart
=> [generator] update `ignore_for_file` rule 

generator/lib/retrofit_generator.dart, generator/lib/src/generator.dart, generator/pubspec.yaml, generator/test/generator_test.dart, generator/test/src/generator_test_src.dart
How about to add [lints](https://pub.dev/packages/lints) to this both projects?
#507
=> [retrofit_generator] Fix error with code_builder

.gitignore, generator/lib/src/generator.dart, generator/test/src/generator_test_src.dart
=> fix: remove null return for void function

README.md, docs/index.html, example/lib/example.dart, example/pubspec.yaml, example/test/example_test.dart, example_dartmapper/bin/main.dart, example_dartmapper/lib/example.dart, example_dartmapper/lib/json_mapper_example.dart, example_dartmapper/test/example_test.dart, flutter_example/android/app/build.gradle, flutter_example/android/app/src/main/AndroidManifest.xml, flutter_example/android/build.gradle, flutter_example/android/gradle/wrapper/gradle-wrapper.properties, flutter_example/lib/example.dart, flutter_example/lib/example.g.dart, flutter_example/lib/mock_adapter.dart, generator/lib/src/generator.dart, generator/pubspec.yaml, generator/test/src/generator_test_src.dart, retrofit/lib/dio.dart, retrofit/pubspec.yaml
Changed dio with diox, Please review once and let me know if any changes are required.
=> Replaced dio with diox

README.md, example/pubspec.yaml, generator/CHANGELOG.md, generator/pubspec.yaml, retrofit/CHANGELOG.md, retrofit/pubspec.yaml
=> Update dio to ^5.0.0

example_protobuf/.gitignore, example_protobuf/.metadata, example_protobuf/README.md, example_protobuf/analysis_options.yaml, example_protobuf/lib/example.dart, example_protobuf/lib/proto/query.pb.dart, example_protobuf/lib/proto/query.pbenum.dart, example_protobuf/lib/proto/query.pbjson.dart, example_protobuf/lib/proto/query.pbserver.dart, example_protobuf/proto/query.proto, example_protobuf/pubspec.yaml, flutter_example/lib/example.g.dart, generator/lib/src/generator.dart, generator/pubspec.yaml, generator/test/src/generator_test_src.dart, generator/test/src/query.pb.dart
add protobuf support
add protobuf test case
close #589
=> feat: add protobuf support

example/build.yaml, example/lib/example.dart, generator/lib/src/generator.dart
Used to publish class ymlp when needed
=> add option class-name custom name retrofit generator

generator/CHANGELOG.md, generator/lib/src/generator.dart, generator/pubspec.yaml
=> Fix generic argument factories support

generator/lib/src/generator.dart, generator/test/generator_test.dart, generator/test/src/generator_test_src.dart
when enabled the analyzer will complain: `The value of 'xxx' should be used.`
=> add @useResult when enabled

generator/lib/src/generator.dart
Reverts trevorwang/retrofit.dart#665
Please submit again  when you finish
=> Revert "Assign data with null safety"

generator/lib/src/generator.dart
I've added BigInt and Long as a basic type which was crucial for a project i'm working on, because the toJson method does not work on BigInt
=> Added BigInt as an 'basictype'

README.md
https://github.com/trevorwang/retrofit.dart/pull/706
=> Add doc section for static extras

generator/lib/src/generator.dart, generator/test/src/generator_test_src.dart
Hi @trevorwang 
This PR fixes issue with `@Body() dynamic user`
=> dynamic body fix

README.md, generator/CHANGELOG.md, generator/lib/retrofit_generator.dart, generator/lib/src/generator.dart, generator/pubspec.yaml, generator/pubspec_overrides.yaml, generator/test/src/generator_test_src.dart, retrofit/CHANGELOG.md, retrofit/lib/call_adapter.dart, retrofit/lib/dio.dart, retrofit/lib/http.dart, retrofit/lib/retrofit.dart, retrofit/pubspec.yaml
This is preparation for `Element2`. 
```
This is part of the old analyzer element model. Please see
https://github.com/dart-lang/sdk/blob/main/pkg/analyzer/doc/element_model_migration_guide.md
for information about how to migrate to the new element model.
```
And also format code.
=> Update dependencies and `build`

example/pubspec.yaml, generator/CHANGELOG.md, generator/lib/src/generator.dart, generator/pubspec.yaml
ref https://github.com/dart-lang/build/issues/3812#issuecomment-2641576908
In projects where `page_width` is set to a value other than 80, running dart format will reapply the format to the generated code. To avoid this behavior, I have added comments to the formatted code.
<details>
<summary>before: example/lib/auth_client.g.dart</summary>
```dart
// GENERATED CODE - DO NOT MODIFY BY HAND
part of 'auth_client.dart';
// **************************************************************************
// RetrofitGenerator
// **************************************************************************
// ignore_for_file: unnecessary_brace_in_string_interps,no_leading_underscores_for_local_identifiers,unused_element,unnecessary_string_interpolations,unused_element_parameter
class RestClientYmlp …
```
=> Add `// dart format off` and `// dart format on` comments to `*.g.dart` file
